<script type="text/javascript" src="<?=BASE_URL?>js/Graph.js"></script>
<script type="text/javascript" src="<?=BASE_URL?>js/nodes.js"></script>
<script>
    var pathsId = '<?=$this->pathsId?>';
    var pathsGroups = [], storeNodes, storeLinks;
    dojo.require("dijit/MenuBar");
    dojo.require("dijit/PopupMenuBarItem");
</script>
<style type="text/css">
/*@import "/dojotoolkit/dojox/widget/Toaster/Toaster.css"; */
.movable { cursor: pointer; }
.dijitTabPane { top: 0px !important; }

#mainTabModulelogica10 {
    background-color: #fff !important;
}
@media print
{
body * { visibility: hidden; }
    #<?=$this->domPrefix?>gfx_holder * { visibility: visible; }
    #<?=$this->domPrefix?>gfx_holder { position: absolute; top: 0px; }
}
/*Lets start with the cloud formation rather*/

/*The container will also serve as the SKY*/

*{ margin: 0; padding: 0;}

body {
	/*To hide the horizontal scroller appearing during the animation*/
	overflow: hidden;
}


#clouds{
	padding: 100px 0;
	position: absolute;
	z-index: -1;
	top: 120px;
	/*	background: #c9dbe9;
	background: -webkit-linear-gradient(top, #c9dbe9 0%, #fff 100%);
	background: -linear-gradient(top, #c9dbe9 0%, #fff 100%);
	background: -moz-linear-gradient(top, #c9dbe9 0%, #fff 100%);*/
}

/*Time to finalise the cloud shape*/
.cloud {
	width: 200px; height: 60px;
	background: #fff;
	z-index: 0;
	border-radius: 200px;
	-moz-border-radius: 200px;
	-webkit-border-radius: 200px;
	
	position: relative; 
}

.cloud:before, .cloud:after {
	content: '';
	position: absolute; 
	background: #fff;
	width: 100px; height: 80px;
	position: absolute; top: -15px; left: 10px;
	
	border-radius: 100px;
	-moz-border-radius: 100px;
	-webkit-border-radius: 100px;
	
	-webkit-transform: rotate(30deg);
	transform: rotate(30deg);
	-moz-transform: rotate(30deg);
}

.cloud:after {
	width: 120px; height: 120px;
	top: -55px; left: auto; right: 15px;
}

/*Time to animate*/
.x1 {
	-webkit-animation: moveclouds 15s linear infinite;
	-moz-animation: moveclouds 15s linear infinite;
	-o-animation: moveclouds 15s linear infinite;
}

/*variable speed, opacity, and position of clouds for realistic effect*/
.x2 {
	left: 200px;
	
	-webkit-transform: scale(0.6);
	-moz-transform: scale(0.6);
	transform: scale(0.6);
	opacity: 0.6; /*opacity proportional to the size*/
	
	/*Speed will also be proportional to the size and opacity*/
	/*More the speed. Less the time in 's' = seconds*/
	-webkit-animation: moveclouds 25s linear infinite;
	-moz-animation: moveclouds 25s linear infinite;
	-o-animation: moveclouds 25s linear infinite;
}

.x3 {
	left: -250px; top: -200px;
	
	-webkit-transform: scale(0.8);
	-moz-transform: scale(0.8);
	transform: scale(0.8);
	opacity: 0.8; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 20s linear infinite;
	-moz-animation: moveclouds 20s linear infinite;
	-o-animation: moveclouds 20s linear infinite;
}

.x4 {
	left: 470px; top: -250px;
	
	-webkit-transform: scale(0.75);
	-moz-transform: scale(0.75);
	transform: scale(0.75);
	opacity: 0.75; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 18s linear infinite;
	-moz-animation: moveclouds 18s linear infinite;
	-o-animation: moveclouds 18s linear infinite;
}

.x5 {
	left: -150px; top: -150px;
	
	-webkit-transform: scale(0.8);
	-moz-transform: scale(0.8);
	transform: scale(0.8);
	opacity: 0.8; /*opacity proportional to the size*/
	
	-webkit-animation: moveclouds 20s linear infinite;
	-moz-animation: moveclouds 20s linear infinite;
	-o-animation: moveclouds 20s linear infinite;
}

@-webkit-keyframes moveclouds {
	0% {margin-left: 1000px;}
	100% {margin-left: -1000px;}
}
@-moz-keyframes moveclouds {
	0% {margin-left: 1000px;}
	100% {margin-left: -1000px;}
}
@-o-keyframes moveclouds {
	0% {margin-left: 1000px;}
	100% {margin-left: -1000px;}
}
</style>
<!-- Menu -->
<div id="mainMenu" data-dojo-type="dijit/MenuBar" style="position:fixed;">
    <div data-dojo-type="dijit/PopupMenuBarItem">
        <span>Zoom</span>
        <div data-dojo-type="dijit/Menu" onclick="">
            <div id="<?=$this->domPrefix?>verticalSlider" data-dojo-type="dijit/form/VerticalSlider"
                value="1" minimum="0.2" maximum="1" 
                intermediateChanges="true"
                showButtons="true" style="height:200px;" name="verticalSlider" onchange="zoomCanvas(this.value, <?=$this->pathsId?>, '<?=$this->domPrefix?>gfx_holder')">
                <ol data-dojo-type="dijit/form/VerticalRuleLabels" container="leftDecoration"
                    style="width:1.5em;font-size:75%;color:gray;">
                    <li></li>
                    <li>40%</li>
                    <li></li>
                    <li>80%</li>
                    <li></li>
                </ol>
                <div data-dojo-type="dijit/form/VerticalRule" container="rightDecoration"
                    count="9" style="width:5px;"></div>
                <ol data-dojo-type="dijit/form/VerticalRuleLabels" container="rightDecoration"
                    style="width:1.5em;font-size:75%;color:gray;">
                    <li>20%</li>
                    <li></li>
                    <li>60%</li>
                    <li></li>
                    <li>100%</li>
                </ol>
            </div>
        </div>
    </div>
    <div data-dojo-type="dijit/PopupMenuBarItem">
        <span>Nodos</span>
        <div data-dojo-type="dijit/Menu">
            <div data-dojo-type="dijit/MenuItem" onclick="
                var form = new zwei.Form({
                    component: 'nodes.xml',
                    ajax: true,
                    action: 'add',
                    dijitDialog: dijit.byId('nodes_xmldialog_add'), 
                    dijitForm: dijit.byId('nodes_xmlform_add'),
                    queryParams: 'paths_id=' + pathsId
                }); 
                form.showDialog();
                ">
                Nuevo Nodo...
            </div>
        </div>
    </div>
    <div data-dojo-type="dijit/PopupMenuBarItem">
        <span>Enlaces</span>
        <div data-dojo-type="dijit/Menu">
            <div data-dojo-type="dijit/MenuItem" onclick="
                var form = new zwei.Form({
                    component: 'links.xml',
                    ajax: true,
                    action: 'add',
                    dijitDialog: dijit.byId('links_xmldialog_add'), 
                    dijitForm: dijit.byId('links_xmlform_add'),
                    queryParams: 'paths_id=' + pathsId
                }); 
                form.showDialog();
                ">
                Nuevo Enlace...
            </div>
        </div>
    </div>
    <div data-dojo-type="dijit/PopupMenuBarItem">
        <span>Recorrer</span>
        <div data-dojo-type="dijit/Menu">
            <div data-dojo-type="dijit/MenuItem" onclick="
                var myDialog = dijit.byId('nodes_xmldialog_findpath');
                myDialog.setHref(base_url + '/components/nodes-graph/paths-dialog?paths_id=' + pathsId);
                myDialog.show();
                ">
                Desde origen a destino.
            </div>
        </div>
    </div>
    <div data-dojo-type="dijit/MenuBarItem" onclick="window.print();">
        Imprimir...
    </div>
</div>
<!-- /Menu -->
<div id="clouds">
	<div class="cloud x1"></div>
	<div class="cloud x2"></div>
	<div class="cloud x3"></div>
	<div class="cloud x4"></div>
	<div class="cloud x5"></div>
</div>
<!-- Dialogos Formularios Mensajes -->
<div id="<?=$this->domPrefix?>gfx_holder" jsId="gfxHolder" class="canvas" style="width: 100%; height: 100%;"></div>
<div dojoType="dijit.Dialog" id="<?=$this->domPrefix?>dialog_add" jsId="<?=$this->domPrefix?>dialog_add" title="Nuevo Nodo" onload="globalOpc='add';" >
</div>
<div dojoType="dijit.Dialog" id="<?=$this->domPrefix?>dialog_edit" jsId="<?=$this->domPrefix?>dialog_edit" refreshOnShow="true" title="Editar Nodo"  onload="globalOpc='edit';"  >
</div>
<!-- Dialogos Formularios Enlaces -->
<div dojoType="dijit.Dialog" id="<?=$this->domPrefix2?>dialog_add" jsId="<?=$this->domPrefix2?>dialog_add" title="Nuevo Enlace" onload="globalOpc='add';" >
</div>
<div dojoType="dijit.Dialog" id="<?=$this->domPrefix2?>dialog_edit" jsId="<?=$this->domPrefix2?>dialog_edit" refreshOnShow="true" title="Editar Nodo"  onload="globalOpc='edit';"  >
</div>
<div dojoType="dijit.Dialog" id="<?=$this->domPrefix?>dialog_findpath" jsId="<?=$this->domPrefix?>dialog_findpath" refreshOnShow="true" title="Buscar Caminos" >
</div>
<div id="log" style="width:600px;height:300px;overflow: auto;"></div>
<script>
dojo.addOnLoad(function(){
    initGfx('<?=$this->domPrefix?>');
    pathsGroups[<?=$this->pathsId?>] = surface.createGroup();
    
    var response = {'more': {'data' : {'title' : ''}} };
    /*
    storeNodes = new dojo.data.ItemFileReadStore({
        url: base_url + 'crud-request?model=NodesModel&primary[pathsId]=<?=$this->pathsId?>&format=json&p=nodes.xml'
    });
    
    storeNodes.fetch({
        onComplete: function(items, request){
            dojo.forEach(items, function(i){
                response.more.data.title = storeNodes.getValues(i, "title")[0];
                addNode(
                    response, 
                    storeNodes.getValues(i, "id")[0], 
                    <?=$this->pathsId?>, 
                    storeNodes.getValues(i, "x")[0], 
                    storeNodes.getValues(i, "y")[0], 
                    true
                );
            });
        },
        onError: function(e){
            alert(e.message);
        }
    });
    
    storeLinks = new dojo.data.ItemFileReadStore({
        url: base_url + 'objects?model=links&paths_id=<?=$this->pathsId?>&format=json'
    });
    */
<?php 
    foreach ($this->nodes as $v) :
?>
    response.more.data.title = '<?=$v->title?>';
    addNode(response, <?=$this->pathsId?>, '<?=$v->id?>', <?=$v->x?>, <?=$v->y?>, true);
<?php 
    endforeach;
?>
<?php 
    foreach ($this->links as $v) :
?>
    addLine(<?=$v->id?>, <?=$this->pathsId?>, <?=$v->nodes_id_from?>, <?=$v->nodes_id_to?>, <?=$v->cost?>);
<?php 
    endforeach;
?>
    var timeout = setTimeout(function () {
        if (typeof(dojo.cookie("scale")) != 'undefined') {
            dijit.byId("<?=$this->domPrefix?>verticalSlider").set('value', parseFloat(dojo.cookie("scale")));
            clearTimeout(timeout);
        }
        dojo.forEach(circles, function(c){
            if (c != undefined)
                c.moveToFront();
        });
        dojo.forEach(circlesLabels, function(cl){
            if (cl != undefined)
                cl.moveToFront();
        });
    }, 500);
});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42061953-1', 'donmostro.com');
  ga('send', 'pageview');

</script>